version: 0.0
os: linux
files:
  - source: /simple
    destination: /home/ubuntu/aws-codedeploy
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/execute.sh
      timeout: 300
      runas: ubuntu